name: OneClient Release Build

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest # ARM
            args: --target aarch64-apple-darwin
          - platform: macos-latest # Intel
            args: --target x86_64-apple-darwin
          - platform: ubuntu-22.04
            args: ''
          - platform: windows-latest
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          target: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
          save-cache: true
          restore-cache: true

      - name: Add x86_64-apple-darwin target
        if: contains(matrix.args, 'x86_64-apple-darwin')
        run: rustup target add x86_64-apple-darwin

      - name: Setup Packages
        uses: ./.github/actions/setup-packages

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: oneclient-__VERSION__
          releaseName: OneClient __VERSION__
          releaseDraft: true
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-alpha') || false }}
          tauriScript: pnpm -w oneclient:desktop
          args: ${{ matrix.args }}
          projectPath: ./apps/oneclient/desktop/
          uploadUpdaterJson: true
